### ISSUE TITLE
Add more categories and data in each category in strings.xml file

### ISSUE THREAD

**Issue by amangrobo** [dsciitpatna/Shabd#105]
**Actual Behaviour**

Currently, there are limited data for display.

**Expected Behaviour**

Expand the database by adding categories and words in each category in the same manner as already done in it.

![Screenshot (1)](https://user-images.githubusercontent.com/34675420/55448758-a9231b00-55e6-11e9-9fd7-0441f54d21e4.png)

**Comment by atm1504** [comment]
@amangrobo keep all the images in firebase storage. Don't scatter it every where.
