### ISSUE TITLE
RuntimeException :A TaskDescription's primary color should be opaque

### ISSUE THREAD

**Issue by VishalBhosale5** [dsciitpatna/Shabd#113]
**Actual Behaviour**
App crashes with RuntimeException: A TaskDescription's primary color should be opaque

**Steps to reproduce it**

- we cannot use  Alpha in primary color so change it to opaque.

**LogCat for the issue**

    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dsciitp.shabd/com.dsciitp.shabd.MainActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque

**Would you like to work on the issue?**

Yes

**Comment by amangrobo** [comment]
We are not getting this issue you mentioned
