### ISSUE TITLE
Implement Oxford dictionary api to search mening of words.

### ISSUE THREAD

**Issue by atm1504** [dsciitpatna/Shabd#123]
**Expected Behaviour**
Add the oxford dictionary api, so that user can search for meanings in the app.

**Steps to reproduce it**
* Get api key from oxford university
* Implement it in the app

**Would you like to work on the issue?**
Yes

**Comment by amangrobo** [comment]
Oxford's API is paid, there are only a limited no of requests available in the free one

**Comment by atm1504** [comment]
Itss good for demo purpose. If our project get selected we will have the commercial version. No of request won't matter a lot now

**Comment by chanmol1999** [comment]
I think this issue can be closed @atm1504 .
