### ISSUE TITLE
Implement youtube api to see video in the app.

### ISSUE THREAD

**Issue by atm1504** [dsciitpatna/Shabd#124]
**Actual Behaviour**
Implement the youtube api, to checkout certain videos related to the various categories inside the app itself

**Expected Behaviour**
* Get api key
* Implement it in the app.

**Would you like to work on the issue?**
Yes

**Comment by chanmol1999** [comment]
@atm1504 What's the status?

**Comment by atm1504** [comment]
@chanmol1999 I will make the pr. It works for one video of the recycler video. I hope u can correct it bit, and make it fit so that it works for all the video. DO use the api key, that will be written
