### ISSUE TITLE
Load JSON from other place rather than from firebase when downloading data initially

### ISSUE THREAD

**Issue by amangrobo** [dsciitpatna/Shabd#131]

**Comment by atm1504** [comment]
What you want to say with this issue?

**Comment by amangrobo** [comment]
Main data JSON will be loaded from Github repo because we don't need realtime updating of that data stored offline in Realm

**Comment by atm1504** [comment]
okk. Then what about the special words that will appear during some events?

**Comment by amangrobo** [comment]
> okk. Then what about the special words that will appear during some events?

that will be loaded from Firestore

**Comment by atm1504** [comment]
Go ahead. No problem.
