### ISSUE TITLE
Store login details like username, user image using pref manager.

### ISSUE THREAD

**Issue by atm1504** [dsciitpatna/Shabd#151]
**Actual Behaviour**
Currently the app reloads user details every time, user opens the profile page. Enable offline persistence of this datas using preference manager.

**Comment by amangrobo** [comment]
No need, it's already loaded offline in firebase auth manager, we don't need to load it everytime.

**Comment by atm1504** [comment]
I have checked it. It's not storing properly. It is refreshing everytime. So I prefer just store it in some pref manager, and display it.
