### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Bhavnaharitsa** [dsciitpatna/Shabd#161]
Update the readme with the list of mentors and contributions at the bottom of the file.

**Would you like to work on the issue?**
Anyone can take up the issue. It's a simple thing.

**Comment by Ashgo18** [comment]
Shall I make PR on this as the Previous Pr has been closed.
Can you please tell me the exact details to be mentioned in the team members.

**Comment by Bhavnaharitsa** [comment]
Go ahead. The list in available on the WhatsApp group
