### ISSUE TITLE
Unable to sign in via google sign in

### ISSUE THREAD

**Issue by Pritom14** [dsciitpatna/Shabd#173]
**Actual Behaviour**

Clicking on the Google Sign in button opens up the accounts for google signin and then displays a `Toast Message` Login failed 

**Expected Behaviour**

Clicking on a google account should log in to the application

**Comment by chanmol1999** [comment]
It is working fine.The reason behind your unsuccessful login is that when we clone and build apps , our project has a SHA1 fingerprint which is different for different users.So the SHA1 fingerprints of particular app joined to firebase,only users will be able to login into that particular app.You can use methods to get inside app without sign in by placing intent filter in manifest at main activity. Thanku :)
