### ISSUE TITLE
create proper options in bottom navigation

### ISSUE THREAD

**Issue by amangrobo** [dsciitpatna/Shabd#18]
sample idea is uploaded below

* home
* quick
* learn
* dictionary
* setting

![IMG_20190309_194441](https://user-images.githubusercontent.com/34675420/54088268-55743780-4382-11e9-95e0-0129bc9fcc57.jpg)

**Comment by chanmol1999** [comment]
Can i work on it ?

**Comment by somenath1435** [comment]
@chanmol1999 good luck

**Comment by atm1504** [comment]
@chanmol1999 go ahead.
