### ISSUE TITLE
create "Speak line" bar at top

### ISSUE THREAD

**Issue by amangrobo** [dsciitpatna/Shabd#20]
* Play button on the left
* Clear button on the right

Sample is uploaded below

![WhatsApp Image 2019-03-10 at 10 28 01 PM](https://user-images.githubusercontent.com/34675420/54088404-e0a1fd00-4383-11e9-83fc-595b5bb83ff8.jpeg)

**Comment by atm1504** [comment]
I am working on it

**Comment by atm1504** [comment]
Currently I am not working on it. So I recommend any of the beginners to take up this issue.
