### ISSUE TITLE
Add cards of various topics in main page

### ISSUE THREAD

**Issue by atm1504** [dsciitpatna/Shabd#32]
**Expected Behaviour**
Add cards of various topics in the home page

**Steps to reproduce it**
* Add firestore documents. This will be used to make cards.
* Make cards and display them in the home fragment.

**Would you like to work on the issue?**
Yes

**Comment by amangrobo** [comment]
needs to be done in firebase firestore

**Comment by atm1504** [comment]
@amangrobo will do it soon
