### ISSUE TITLE
Create a basic layout for settings fragment .

### ISSUE THREAD

**Issue by chanmol1999** [dsciitpatna/Shabd#43]
Sample options for Settings include:
* Profile
* logout
* language
* Miscellaneous include developers/About app,rate app,share app,
* Daily Suggestions
* TextToSpeech intent to system tts

**Comment by atm1504** [comment]
We are going to use PrefernceScreen to make the settings page. 

The related sources of documentation are:
* https://developer.android.com/reference/android/preference/PreferenceScreen
* https://developer.android.com/guide/topics/ui/settings
* https://code.tutsplus.com/tutorials/how-to-code-a-settings-screen-in-an-android-app--cms-30433
* https://youtu.be/0-7YvU9fz8k

**Comment by aparsh** [comment]
i am working on it
