### ISSUE TITLE
Change the background colour of the fragments, tts bar

### ISSUE THREAD

**Issue by atm1504** [dsciitpatna/Shabd#54]
**Actual Behaviour**
Currently the background colour of the fragments are default colour.

**Expected Behaviour**
Change the background colour to look more attractive. Use some gradients. Also change the background colour of the tts bar in home fragment. Make it transparent.

**Steps to reproduce it**
Make gradients and use it as background colour.

**Resources to implement this feature:**
* https://www.youtube.com/watch?v=UJAuWf4p8qI
* https://www.youtube.com/watch?v=e6YZFGCzqwk

**Comment by VishalBhosale5** [comment]
Can I take up this issue?.

**Comment by atm1504** [comment]
Go ahead

**Comment by VishalBhosale5** [comment]
hello Sir,i mailed you regrading this issue.

**Comment by amangrobo** [comment]
You can take up any issue you like.
If you are working on something of your own, make sure you create an issue about the problem and follow PR guidelines.

**Comment by VishalBhosale5** [comment]
this project has many runtime exceptions do i need to clear it or just work on this background color issue?

**Comment by amangrobo** [comment]
> this project has many runtime exceptions do i need to clear it or just work on this background color issue?

Told you,  just make an issue about any runtime exception you find and work on it if you like to solve it.

**Comment by atm1504** [comment]
@VishalBhosale5 what's the status of this issue?

**Comment by VishalBhosale5** [comment]
I'm working on it sir.
