### ISSUE TITLE
Add proper Internalisation support for text

### ISSUE THREAD

**Issue by fliptrail** [dsciitpatna/Shabd#83]
I suggest that there should be proper internationalisation support to enable multiple languages. Over the course of time, I have realized that the sooner all the text gets internationalised the better it is. 

References: https://developer.android.com/guide/topics/resources/localization, https://lingohub.com/frameworks-file-formats/android-i18n-android-studio/

I suggest that this would be very helpful in scaling up the app.

PS: if it still not your priority right now, feel free to close this issue.

**Would you like to work on the issue?**

No

**Comment by amangrobo** [comment]
It's already done, the strings are being loaded from a separate file and are nor being hardcoded(except a few cases, which will be corrected soon). I have also added a few words in the Hindi language yet.

**Comment by fliptrail** [comment]
> It's already done, the strings are being loaded from a separate file and are nor being hardcoded(except a few cases, which will be corrected soon). I have also added a few words in the Hindi language yet.

Feel free to close this, when it is done
