### ISSUE TITLE
Add screenshots of the current state of app in readme file.

### ISSUE THREAD

**Issue by atm1504** [dsciitpatna/Shabd#89]
**Actual Behaviour**
Add screenshots of the current state of app in readme file.

**Comment by aparsh** [comment]
i am working on it.

**Comment by atm1504** [comment]
@aparsh what's the status? Give it a priority and do this.

**Comment by ajirk** [comment]
@atm1504 can I take up this issue?

**Comment by atm1504** [comment]
@ajirk go ahead.
